#spring.application.name=spring-boot-monolithic-starter

server:
  port: 8080

spring:

  application:
    name: spring-boot-monolithic-starter

  datasource:
    url: jdbc:mysql://localhost:3307/local_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: app_user
    password: app_user_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true          # SQL ?? ??
        format_sql: true        # SQL ??? ?? ???
        use_sql_comments: true  # ?? ??? ??(?? ????? ????? ?) ??

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework: INFO
